# Shared home-manager config for macOS and Linux.
#
# Configs are symlinked straight to the repo checkout ("out-of-store"), so
# editing ~/.config/<app>/... edits the repo and takes effect immediately; no
# rebuild. Rebuild (`dot switch`) only when you add/remove a linked file or
# change anything under nix/.
{
  config,
  lib,
  pkgs,
  user,
  ...
}:
let
  repo = "${config.home.homeDirectory}/${user.dotfiles}";
  link = path: config.lib.file.mkOutOfStoreSymlink "${repo}/config/${path}";

  # Link every file under config/<src> individually into ~/.config/<dst>, so
  # other tools (fisher) can keep their own files in the same directories.
  linkEach =
    src: dst:
    lib.listToAttrs (
      map (
        file:
        let
          rel = lib.removePrefix "${toString ../../config}/${src}/" (toString file);
        in
        lib.nameValuePair "${dst}/${rel}" { source = link "${src}/${rel}"; }
      ) (lib.filesystem.listFilesRecursive (../../config + "/${src}"))
    );
in
{
  # Shared with darwin.nix / linux.nix.
  _module.args.dot = { inherit link linkEach; };

  home.stateVersion = "26.11";

  home.packages = import ./packages.nix pkgs ++ [
    # `dot` helper (switch/update/drift/...), run live from the repo.
    (pkgs.writeShellScriptBin "dot" ''exec "${repo}/bin/dot" "$@"'')
  ];

  xdg.configFile =
    linkEach "fish/functions" "fish/functions"
    // linkEach "fish/conf.d" "fish/conf.d"
    // {
      "fish/config.fish".source = link "fish/config.fish";
      "fish/fish_plugins".source = link "fish/fish_plugins";

      # Whole directories (the app only keeps config in them).
      "nvim".source = link "nvim";
      "git".source = link "git";
      "mise".source = link "mise";
      "atuin".source = link "atuin";
      "bat".source = link "bat";
      "btop".source = link "btop";
      "lsd".source = link "lsd";
      "spotify-player".source = link "spotify-player";
      "1Password/ssh".source = link "1Password/ssh";

      # Single files (the directory also holds local state/credentials).
      "starship.toml".source = link "starship.toml";
      "gh/config.yml".source = link "gh/config.yml";
      "ghostty/config".source = link "ghostty/config";
      # Per-machine Ghostty bits generated by Nix (loaded via `config-file` in ghostty/config).
      "ghostty/nix.conf".text = ''
        command = ${pkgs.fish}/bin/fish --login
      '';
    };

  # Install/update fisher plugins whenever config/fish/fish_plugins changes.
  home.activation.fisher = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    plugins="${config.xdg.configHome}/fish/fish_plugins"
    stamp="${config.xdg.stateHome}/dotfiles/fish_plugins.sha256"
    want="$(${pkgs.coreutils}/bin/sha256sum "$plugins" | ${pkgs.coreutils}/bin/cut -d' ' -f1)"
    if [ "$(cat "$stamp" 2>/dev/null)" != "$want" ]; then
      echo "fish_plugins changed; running fisher update"
      if PATH="${config.home.path}/bin:${
        lib.makeBinPath [
          pkgs.curl
          pkgs.gnutar
          pkgs.gzip
          pkgs.coreutils
        ]
      }:$PATH" run ${pkgs.fish}/bin/fish -c '
          functions -q fisher
          or curl -fsSL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
          and fisher update'; then
        run mkdir -p "$(dirname "$stamp")"
        [ -n "''${DRY_RUN:-}" ] || echo "$want" > "$stamp"
      else
        echo "warning: fisher update failed; run 'fisher update' in fish" >&2
      fi
    fi
  '';
}
